// <auto-generated />
using System;
using EscolaDeCursosWebApp.Compartilhado.Infra.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaDeCursosWebApp.Migrations
{
    [DbContext(typeof(EscolaDeCursosDbContext))]
    [Migration("20260713053644_AddCategoria")]
    partial class AddCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.HasIndex("nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBCategoria_Nome");

                    b.ToTable("TBCategoria", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloUsuario.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBUsuario");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBUsuario_Email");

                    b.HasIndex("telefone")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBUsuario_Telefone");

                    b.ToTable("TBUsuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
