// <auto-generated />
using System;
using EscolaDeCursosWebApp.Compartilhado.Infra.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaDeCursosWebApp.Migrations
{
    [DbContext(typeof(EscolaDeCursosDbContext))]
    [Migration("20260714024500_AddAlunoNotasPresencas")]
    partial class AddAlunoNotasPresencas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_TBAluno");

                    b.ToTable("TBAluno", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.NotaAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoNota")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id")
                        .HasName("PK_TBNotaAluno");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("IX_TBNotaAluno_AlunoId");

                    b.HasIndex("MatriculaId", "TipoNota")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBNotaAluno_MatriculaId_TipoNota");

                    b.ToTable("TBNotaAluno", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.PresencaAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAula")
                        .HasColumnType("date");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_TBPresencaAluno");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("IX_TBPresencaAluno_AlunoId");

                    b.HasIndex("MatriculaId", "DataAula")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBPresencaAluno_MatriculaId_DataAula");

                    b.ToTable("TBPresencaAluno", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.HasIndex("nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBCategoria_Nome");

                    b.ToTable("TBCategoria", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloCurso.Dominio.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cargaHoraria")
                        .HasColumnType("int");

                    b.Property<Guid>("categoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("nivelDificuldade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK_TBCurso");

                    b.HasIndex("nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBCurso_Nome");

                    b.ToTable("TBCurso", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloMatricula.Dominio.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Nota1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Nota2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Nota3")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Recuperacao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_TBMatricula");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("IX_TBMatricula_AlunoId");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("IX_TBMatricula_TurmaId");

                    b.ToTable("TBMatricula", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloProfessor.Dominio.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("date");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_TBProfessorPerfil");

                    b.ToTable("TBProfessorPerfil", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloTurma.Dominio.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HorarioTurno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("cursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("instrutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("vagasMaximas")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBTurma");

                    b.HasIndex("nome")
                        .HasDatabaseName("IX_TBTurma_Nome");

                    b.ToTable("TBTurma", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloUsuario.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBUsuario");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBUsuario_Email");

                    b.HasIndex("telefone")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBUsuario_Telefone");

                    b.ToTable("TBUsuario", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", b =>
                {
                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloUsuario.Dominio.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBAluno_TBUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.NotaAluno", b =>
                {
                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBNotaAluno_TBAluno");

                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloMatricula.Dominio.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBNotaAluno_TBMatricula");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.PresencaAluno", b =>
                {
                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", "Aluno")
                        .WithMany("Presencas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBPresencaAluno_TBAluno");

                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloMatricula.Dominio.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBPresencaAluno_TBMatricula");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloProfessor.Dominio.Professor", b =>
                {
                    b.HasOne("EscolaDeCursosWebApp.Modulos.ModuloUsuario.Dominio.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("EscolaDeCursosWebApp.Modulos.ModuloProfessor.Dominio.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBProfessorPerfil_TBUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscolaDeCursosWebApp.Modulos.ModuloAluno.Dominio.Aluno", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Presencas");
                });
#pragma warning restore 612, 618
        }
    }
}